In [13]:
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a[:,:,None].shape)

(3, 3)
(3, 3, 1)


In [7]:
print(a[:, None])

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [40]:
import numpy as np
mask1= np.array([[1,0,1],[1,1,0]]).T
mask2= np.array([[0,1,0],[0,1,1]]).T
mask1 = np.reshape(mask1, (-1,2)).astype(np.float32)
mask2 = np.reshape(mask2, (-1,2)).astype(np.float32)	
area1 = np.sum(mask1, axis=0)  
area2 = np.sum(mask2, axis=0)	
# intersections and union
intersections = np.dot(mask1.T, mask2) 
union = area1[:, None] + area2[None, :] - intersections

In [41]:
print(mask1)
print(mask2)
print(area1,'\n',area2,'\n')

[[1. 1.]
 [0. 1.]
 [1. 0.]]
[[0. 0.]
 [1. 1.]
 [0. 1.]]
[2. 2.] 
 [1. 2.] 



In [44]:
print(mask1.T)
print(mask2)
np.dot(mask1.T, mask2) 

[[1. 0. 1.]
 [1. 1. 0.]]
[[0. 0.]
 [1. 1.]
 [0. 1.]]


array([[0., 1.],
       [1., 1.]], dtype=float32)

In [39]:
print(union)

[[3. 3.]
 [2. 3.]]


In [27]:
print( area1[:, None])

[[2.]
 [2.]]


In [28]:
print( area2[None, :] )

[[1. 2.]]


In [29]:
print( area1[:, None] + area2[None, :])

[[3. 4.]
 [3. 4.]]


In [45]:
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[a>3])

[4 5 6 7 8 9]


In [46]:
index = np.where(a!= 1)

In [47]:
print(index)

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))


In [48]:
a[index]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
dict = {3: 5, 2: 2}

In [15]:
a=dict.values()

In [19]:
b=list(dict.values())

In [20]:
print(b)

[5, 2]


In [5]:
import numpy as np
x=np.array(range(9)).reshape(3,3)
print(x)
x_pad = np.pad(x, ((0,), (0,), (1,), (1,)), mode='constant', constant_values=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (4,1) and requested shape (2,2)